# -*- coding: utf-8 -*-
"""model_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZwzQtsCeZCOkP9VErLSr2XLl6U7LaEv
"""

import sys
sys.path.insert(0, '/content/drive/MyDrive/Question 5 - ML/src')
sys.path.insert(0, '/content/drive/MyDrive/Question 5 - ML/pipelines')


import pandas as pd
import pickle



def load_model_and_predict(store, item_dept, date, history_file):
    # Load the model from disk
    file_path = 'C:/Users/mariy/Downloads/Question 5 - ML-20240829T070211Z-001/Question 5 - ML/pipelines/xgboost_model.pkl'
    
    model = pickle.load(open(file_path, 'rb'))
    # Load historical data from CSV with date parsing
    history = pd.read_csv(history_file, parse_dates=['date_id'], index_col='date_id')

    # Ensure the date is a datetime object
    date = pd.to_datetime(date)

    # Filter historical data for the specific store, department, and date
    input_data = history[(history['store'] == store) &
                         (history['item_dept'] == item_dept) &
                         (history.index.date == date.date())]


    # Select and format the features required by the model
    input_features = input_data[['item_qty_lag_1', 'item_qty_lag_7', 'net_sales_lag_1', 'net_sales_lag_7',
                                 'day_of_week', 'is_weekend', 'month', 'quarter', 'year',
                                 'store_sales_ratio', 'price_per_item']]

   # predicted_qty = model.predict(input_features)
    predicted_qty = model.predict(input_features)
    return predicted_qty[0]
