# -*- coding: utf-8 -*-
"""mainpipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAxy24lrlQsXbY5e4qvwvBLiCMQeACub
"""

import sys

sys.path.insert(0,'/content/drive/MyDrive/Question 5 - ML/src')

from dataprocessing_py import load_data
from features import *



def generate_master_table(transactions_path, outlet_info_path):
    # Load and preprocess data
    data = load_data(transactions_path, outlet_info_path)

    # Aggregate data for all stores and departments
    master_data = aggregate_data(data)

    # Create features
    master_data = create_time_features(master_data)
    master_data = create_lag_features(master_data, lag_days=1)
    master_data = create_lag_features(master_data, lag_days=7)
    master_data = calculate_store_sales_ratio(master_data)
    master_data = calculate_item_features(master_data)

    # Drop any rows with NaN values after feature engineering
    master_data.dropna(inplace=True)

    return master_data

